### ISSUE TITLE
Docs on use with official Caddy Docker images?

### ISSUE THREAD

**Issue by hartwork** [caddyserver/format-encoder#3]
Hi, thanks for making and sharing this extension as software libre!

Are there any docs on how to use it with any of the [official Caddy Docker images](https://hub.docker.com/_/caddy?tab=description)?

Thanks, Sebastian

**Comment by Mohammed90** [comment]
You can use the `builder` image variant. Check the _Adding custom Caddy modules_ section on [Caddy's Docker image page](https://hub.docker.com/_/caddy/).

**Comment by hartwork** [comment]
Okay thanks! Would you be interested in reviewing and merging a pull request extending the readme, once I can conform that this approach works, in general?

**Comment by mholt** [comment]
Extending the readme with what? I'm not sure we should be documenting something as unrelated as Docker in this repo.

**Comment by hartwork** [comment]
Docker is a standard use case for core Caddy server. For someone that uses Caddy through Docker today but has little background in Golang, the current readme doesn't provide any help or pointers on how to get `format-encoder` into plain Docker Caddy life. So what I would add is a section with (a) the link that @Mohammed90 shared or (b) a simple example Dockerfile.
