### ISSUE TITLE
How to output only one User-Agent?

### ISSUE THREAD

**Issue by riku22** [caddyserver/format-encoder#5]
Hello.

I'm trying to log only one from the User-Agent header.
I wrote the following template.

```
format formatted "{{index request>headers>User-Agent 0}}"
```

However, this does not work well, and the character string specified in the format as shown below is output as it is.

```
{{index request>headers>User-Agent 0}}
```

Is it difficult to do this?

The environment is as follows.

- Ubuntu 20.04.1 LTS
- Caddy v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
- github.com/caddyserver/format-encoder v0.0.0-20200619105626-addf3285dafc h1:ql2pYXx8r7+8c48XmOKb1Ui6FmKpEboX3yThQOJ6DwY=

Best regards.

**Comment by Mohammed90** [comment]
The template isn't a Go template, so the usage of double braces and the function `index` isn't correct. The syntax of the template is defined by the backing library [github.com/buger/jsonparser](github.com/buger/jsonparser). For your use-case, you need: `format formatted "{request>headers>User-Agent>[0]}"`.

This is a shortcoming in the documentation of this module. I'll address it in the README shortly.
