### ISSUE TITLE
Use `remote_ip`

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/format-encoder#9]
Right now the rebuilt CLF template has the remote address with the port included due to prior limitation in Caddy JSON log.
https://github.com/caddyserver/format-encoder/blob/cd12651f12fd7329edd69eccfd7c75b93cd13045/formatencoder.go#L35

This can be fixed once caddyserver/caddy#4403 lands.

**Comment by francislavoie** [comment]
caddyserver/caddy#4403 was merged btw, in case you want to prep the PR to merge it at the same time as 2.5.0 releases I guess

**Comment by francislavoie** [comment]
Time to do this! @mohammed90 😁

**Comment by mohammed90** [comment]
Doing it requires explicitly specifying the 2.5.0-beta.1 version as the minimum accepted version. Shall I? 🤔

**Comment by francislavoie** [comment]
I think we should, yeah
